# Changes here will be overwritten by Copier
_commit: 28c66e4
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@ggmail.com
github: tkp-aliases
project_description: Alias for fsspec-rs
project_name: fsspec-rust
python_version_primary: '3.11'
team: the fsspec-rust authors
